### ISSUE TITLE
Very Fist Beta Release

### ISSUE THREAD

**Issue by Lakr233** [Lakr233/ActionBee#1]
See follow up.

~~[ActionBee-v0.1b1.zip](https://github.com/Lakr233/ActionBee/files/9353631/ActionBee-v0.1b1.zip)~~

**Comment by Lakr233** [comment]
Please be patient while we are reviewing code for GitHub release. They source is already opened if you can find it somehow :)

**Comment by Lakr233** [comment]
~~[ActionBee-v0.1b1r2.zip](https://github.com/Lakr233/ActionBee/files/9356321/ActionBee-v0.1b1r2.zip)~~

This release has relaxed sandbox permission for some system library to run, such as NLP (used by NSDataDetector NSTextCheckingResult.CheckingType = .link). Networking is still not allowed, but a controlled proxy is planned.

A sample module for clean url links inside text is provided as follow. If you made progress, please share.

[Module Export - Link Cleaner.zip](https://github.com/Lakr233/ActionBee/files/9356340/Module.Export.-.Link.Cleaner.zip)

**Comment by Lakr233** [comment]
~~[ActionBee-v0.1b1r3.zip](https://github.com/Lakr233/ActionBee/files/9357147/Action.app.zip)~~

This release adds an option to disable module.

**Comment by Officeyutong** [comment]
Write nothing, code nothing!

**Comment by Lakr233** [comment]
~~[ActionBee-v0.1b1r4.zip](https://github.com/Lakr233/ActionBee/files/9357742/ActionBee-v0.1b1r4.zip)~~

This release adds toast mode and a better handle of popover indicator.

**Comment by Lakr233** [comment]
App is in final review for release.
